language: node_js
node_js:
  - 12

install:
  - curl -sf https://up.apex.sh/install | sudo sh
  - npm install -g serverless

deploy:
  - provider: script
    script:
      # up deploy
      serverless deploy
    on:
      all_branches: true
