service: TaskB3

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
  taskB3:
    handler: handler.taskB3
    events:
      - http:
          path: /taskB3
          method: get